# Generated by Django 4.1.2 on 2022-11-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_restaurant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-id"]},
        ),
    ]
